export const imageList: {
  img: string;
  title: string;
  rows?: number;
  cols?: number;
}[] = [
  {
    img: "public/mosaicpics/AnotherWedding.jpeg",
    title: "Filler title",
    rows: 3,
    cols: 2,
  },
  {
    img: "public/mosaicpics/Arletteturns25.jpeg",
    title: "Filler title",
    rows: 3,
    cols: 2,
  },
  {
    img: "public/mosaicpics/Arlie.JPG",
    title: "Filler title",
    rows: 3,
    cols: 2,
  },
  {
    img: "public/mosaicpics/ArtMuseum.jpg",
    title: "Filler title",
    rows: 1,
    cols: 1,
  },
  {
    img: "public/mosaicpics/AtaBar.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 3,
  },
  {
    img: "public/mosaicpics/BigMountains.jpeg",
    title: "Filler title",
    rows: 3,
    cols: 1,
  },
  {
    img: "public/mosaicpics/BikeRiding.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 2,
  },
  {
    img: "public/mosaicpics/Books.JPG",
    title: "Filler title",
    rows: 2,
    cols: 2,
  },
  {
    img: "public/mosaicpics/Brunchwfriends.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 1,
  },
  {
    img: "public/mosaicpics/car1.png",
    title: "Filler title",
    rows: 3,
    cols: 3,
  },
  {
    img: "public/mosaicpics/Carlsbad.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 1,
  },
  {
    img: "public/mosaicpics/CatalinaIsland.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 2,
  },
  {
    img: "public/mosaicpics/ChristmasDinner.jpeg",
    title: "Filler title",
    rows: 3,
    cols: 1,
  },
  {
    img: "public/mosaicpics/closetogether.PNG",
    title: "Filler title",
    rows: 1,
    cols: 3,
  },
  {
    img: "public/mosaicpics/CookingTogether",
    title: "Filler title",
    rows: 2,
    cols: 2,
  },
  {
    img: "public/mosaicpics/CovidAndDinosaurs.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 1,
  },
  {
    img: "public/mosaicpics/DinnerTogether.jpeg",
    title: "Filler title",
    rows: 3,
    cols: 2,
  },
  {
    img: "public/mosaicpics/DisneySea.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 3,
  },
  {
    img: "public/mosaicpics/Driving.JPG",
    title: "Filler title",
    rows: 1,
    cols: 1,
  },
  {
    img: "public/mosaicpics/DuranDuran.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 2,
  },
  {
    img: "public/mosaicpics/FamwithDog.jpeg",
    title: "Filler title",
    rows: 3,
    cols: 3,
  },
  {
    img: "public/mosaicpics/FirstAnniversary.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 1,
  },
  {
    img: "public/mosaicpics/Flowers.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 3,
  },
  {
    img: "public/mosaicpics/GettyFlowers.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 2,
  },
  {
    img: "public/mosaicpics/HavingBoba.JPG",
    title: "Filler title",
    rows: 1,
    cols: 1,
  },
  {
    img: "public/mosaicpics/Hugs.jpeg",
    title: "Filler title",
    rows: 3,
    cols: 2,
  },
  {
    img: "public/mosaicpics/JapanFood.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 2,
  },
  {
    img: "public/mosaicpics/JapanShrine.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 3,
  },
  {
    img: "public/mosaicpics/KissAtGarden.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 1,
  },
  {
    img: "public/mosaicpics/kyoto.jpeg",
    title: "Filler title",
    rows: 3,
    cols: 1,
  },
  {
    img: "public/mosaicpics/KyotoNature.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 2,
  },
  {
    img: "public/mosaicpics/KyotoRiver.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 3,
  },
  {
    img: "public/mosaicpics/KyotoShrine.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 1,
  },
  {
    img: "public/mosaicpics/KyotoTrees.jpeg",
    title: "Filler title",
    rows: 3,
    cols: 3,
  },
  {
    img: "public/mosaicpics/LaJolla.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 1,
  },
  {
    img: "public/mosaicpics/Library.JPG",
    title: "Filler title",
    rows: 1,
    cols: 2,
  },
  {
    img: "public/mosaicpics/MissionBeach.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 2,
  },
  {
    img: "public/mosaicpics/MovingOut.JPG",
    title: "Filler title",
    rows: 3,
    cols: 1,
  },
  {
    img: "public/mosaicpics/Naptime.JPG",
    title: "Filler title",
    rows: 1,
    cols: 1,
  },
  {
    img: "public/mosaicpics/Naptime2.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 3,
  },
  {
    img: "public/mosaicpics/NatureYosemite.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 2,
  },
  {
    img: "public/mosaicpics/OhashiFam.jpeg",
    title: "Filler title",
    rows: 3,
    cols: 2,
  },
  {
    img: "public/mosaicpics/OhashiGarden.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 1,
  },
  {
    img: "public/mosaicpics/OnTheBeach.JPG",
    title: "Filler title",
    rows: 2,
    cols: 2,
  },
  {
    img: "public/mosaicpics/OurFirstApartment.JPG",
    title: "Filler title",
    rows: 1,
    cols: 3,
  },
  {
    img: "public/mosaicpics/OutHiking.jpeg",
    title: "Filler title",
    rows: 3,
    cols: 1,
  },
  {
    img: "public/mosaicpics/Paddleboat.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 1,
  },
  {
    img: "public/mosaicpics/PickingAvocados.JPG",
    title: "Filler title",
    rows: 1,
    cols: 2,
  },
  {
    img: "public/mosaicpics/PicofaPic.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 1,
  },
  {
    img: "public/mosaicpics/PlanetoTulum.jpeg",
    title: "Filler title",
    rows: 3,
    cols: 3,
  },
  {
    img: "public/mosaicpics/QuickDrive.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 2,
  },
  {
    img: "public/mosaicpics/RollerSkating.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 1,
  },
  {
    img: "public/mosaicpics/RyokanYukatas.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 3,
  },
  {
    img: "public/mosaicpics/Sakuras.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 2,
  },
  {
    img: "public/mosaicpics/Shinjuku.jpeg",
    title: "Filler title",
    rows: 3,
    cols: 1,
  },
  {
    img: "public/mosaicpics/Takas27.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 2,
  },
  {
    img: "public/mosaicpics/TakaTurns27.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 1,
  },
  {
    img: "public/mosaicpics/thepier.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 3,
  },
  {
    img: "public/mosaicpics/TulumBeach.jpeg",
    title: "Filler title",
    rows: 3,
    cols: 2,
  },
  {
    img: "public/mosaicpics/TulumRuins.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 1,
  },
  {
    img: "public/mosaicpics/TulumTogether.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 1,
  },
  {
    img: "public/mosaicpics/UnderaGate.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 2,
  },
  {
    img: "public/mosaicpics/Waterfall.jpeg",
    title: "Filler title",
    rows: 1,
    cols: 2,
  },
  {
    img: "public/mosaicpics/yosemite1.jpeg",
    title: "Filler title",
    rows: 3,
    cols: 3,
  },
  {
    img: "public/mosaicpics/yosemite2.jpeg",
    title: "Filler title",
    rows: 2,
    cols: 1,
  },
];
